core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

handler404 = "account.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_product'),
    path('store/about', views.about, name='about'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('shop/', views.shop_product, name='shop')
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.view_list, name='list'),
    path('add/', views.add_wish, name='add'),
    path('delete/', views.delete_wish, name='delete_wish'),
]

wishlist/models.py
from django.conf import settings
from django.db import models

from store.models import Product


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='users_wish', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='product_wish', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return str(self.id)

wishlist/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .models import Wishlist


@login_required
def view_list(request):
    user_id = request.user.id
    wishlist = Wishlist.objects.filter(user=user_id)
    return render(request, 'wishlist/wishlist.html', {'wishlist': wishlist})


def add_wish(request):
    if request.method == 'POST':
        user_id = request.user.id
        product_id = request.POST.get('product_id')
        product_wish = get_object_or_404(Product, id=product_id)
        if Wishlist.objects.filter(product=product_wish, user=user_id).exists():
            response = JsonResponse({'not done': 'object already in wishlist'})
            return response

        else:
            Wishlist.objects.create(user_id=user_id, product=product_wish)
            response = JsonResponse({'success': 'Return something'})
            return response


def delete_wish(request):
    if request.method == 'POST':
        wishlist_id = request.POST.get('wish_id')
        wishlist = get_object_or_404(Wishlist, id=wishlist_id)
        wishlist.delete()
        response = JsonResponse({'success': 'Return something'})
        return response

templates/wishlist/wishlist.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}My Wishlist - Eco Shop{% endblock %}

{% block content %}
<style>
  .img-responsive {
    max-height: 45vh;
    object-fit: cover;
  }

  @media only screen and (max-width: 1280px) {
    .img-responsive {
      max-height: 50vh;
      object-fit: cover;
    }
  }

  @media only screen and (max-width: 768px) {

    /* For mobile phones: */
    .img-responsive {
      max-height: 100%;
      object-fit: cover;
    }
  }
</style>

<section class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="content">
          <h1 class="page-name">Wishlist</h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'store:all_product' %}">Home</a></li>
            <li class="active">my wishlist</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container">
  <div class="row">
    <div class="row">
      <div class="title text-center">
        <h2>Wishlist</h2>
      </div>
    </div>
    {% if not wishlist %}
    <div class="row">
      <div class="title text-center">
        <h4>My Wishlist</h4>
      </div>
    </div>

    {% else %}
    {% for wish in wishlist %}
    <div class="col-md-3 wishlist-item" data-index="{{ wish.id }}">
      <div class="product-item">
        <div class="product-thumb">
          <span class="bage">Sale</span>
          <img class="img-responsive" src="{{ wish.product.image.url }}" alt="product-img" />
          <div class="preview-meta">
            <ul>
              <li>
                <a href="{{ wish.product.get_absolute_url }}"><i class="tf-ion-android-folder"></i></a>
              </li>
              <li>
                <a data-index="{{ wish.id }}" class="delete-wish"><i class="tf-ion-ios-trash"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="product-content">
          <h4><a href="product-single.html">{{ wish.product.title }}</a></h4>
          <p class="price">${{ wish.product.price }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>

<script>
  $(document).on('click', '.delete-wish', function (e) {
    e.preventDefault();
    var wishid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "wishlist:delete_wish" %}',
      data: {
        wish_id: wishid,
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        console.log(json);
        $('.wishlist-item[data-index="' + wishid + '"]').remove();
        showSnackbar("Wish Removed", "#EF1700");
      },
      error: function (xhr, errmsg, err) {
        console.log(err);
      }
    });
  });
</script>
{% endblock %}